version: '3'
services:
  mobsf-db:
    image: postgres:latest
    container_name: mobsf-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mobsf
    volumes:
      - MOBSF_DB_VOL:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - mobsf

  mobsf-app:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mobsf
      - POSTGRES_HOST=mobsf-db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POSTGRES=True
    container_name: mobsf-app
    restart: always
    volumes:
      - MOBSF_APP_VOL:/home/mobsf/.MobSF:rw
    ports:
      - "8000:8000"
    networks:
      - mobsf
    depends_on:
      - mobsf-db

networks:
  mobsf: